// <auto-generated />
using System;
using Artikelsystem.Api.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Artikelsystem.API.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250331115241_DbContextAusgegliedert")]
    partial class DbContextAusgegliedert
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Artikelsystem.Api.Features.Artikel.Models.Entitys.Artikel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Bild")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Maximalbestand")
                        .HasColumnType("integer");

                    b.Property<int>("Menge")
                        .HasColumnType("integer");

                    b.Property<int>("Mindestbestand")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preis")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Artikel");
                });

            modelBuilder.Entity("Artikelsystem.Api.Features.Artikel.Models.Entitys.ArtikelStatistik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DurchschnittlicherEinzelpreis")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DurchschnittlicherVerkaufspreis")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GesamtVerkaufswert")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric")
                        .HasComputedColumnSql("\"VerkaufsMenge\" * \"DurchschnittlicherVerkaufspreis\"", true);

                    b.Property<decimal>("Gesamtmenge")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Lagerwert")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric")
                        .HasComputedColumnSql("\"Gesamtmenge\" * \"DurchschnittlicherEinzelpreis\"", true);

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VerkaufsMenge")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId")
                        .IsUnique();

                    b.ToTable("ArtikelStatistiken");
                });

            modelBuilder.Entity("Artikelsystem.Api.Features.Employees.Models.Entitys.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseCost")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Benefits");
                });

            modelBuilder.Entity("Artikelsystem.Api.Features.Employees.Models.Entitys.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("SocialSecurityNumber")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Artikelsystem.Api.Features.Employees.Models.Entitys.EmployeeBenefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BenefitId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CostToEmployee")
                        .HasColumnType("numeric");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BenefitId");

                    b.HasIndex("EmployeeId", "BenefitId")
                        .IsUnique();

                    b.ToTable("EmployeeBenefits");
                });

            modelBuilder.Entity("Artikelsystem.Api.Features.Lieferant.Models.Entitys.Lieferant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAdresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hausnummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notizen")
                        .HasColumnType("text");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PLZ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lieferanten");
                });

            modelBuilder.Entity("Artikelsystem.Api.Features.Wareneingang.Models.Entitys.Wareneingang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Gesamtpreis")
                        .HasColumnType("numeric");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LieferantId")
                        .HasColumnType("integer");

                    b.Property<int>("Menge")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LieferantId");

                    b.ToTable("Wareneingaenge");
                });

            modelBuilder.Entity("Artikelsystem.Api.Features.Wareneingang.Models.Entitys.WareneingangArtikel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Einzelpreis")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Gesamtpreis")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric")
                        .HasComputedColumnSql("\"Menge\" * \"Einzelpreis\"", true);

                    b.Property<int>("Menge")
                        .HasColumnType("integer");

                    b.Property<int>("WareneingangId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId");

                    b.HasIndex("WareneingangId", "ArtikelId")
                        .IsUnique();

                    b.ToTable("WareneingangArtikel");
                });

            modelBuilder.Entity("Artikelsystem.Api.Features.Artikel.Models.Entitys.ArtikelStatistik", b =>
                {
                    b.HasOne("Artikelsystem.Api.Features.Artikel.Models.Entitys.Artikel", "Artikel")
                        .WithOne("ArtikelStatistik")
                        .HasForeignKey("Artikelsystem.Api.Features.Artikel.Models.Entitys.ArtikelStatistik", "ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");
                });

            modelBuilder.Entity("Artikelsystem.Api.Features.Employees.Models.Entitys.EmployeeBenefit", b =>
                {
                    b.HasOne("Artikelsystem.Api.Features.Employees.Models.Entitys.Benefit", "Benefit")
                        .WithMany()
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artikelsystem.Api.Features.Employees.Models.Entitys.Employee", "Employee")
                        .WithMany("Benefits")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benefit");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Artikelsystem.Api.Features.Wareneingang.Models.Entitys.Wareneingang", b =>
                {
                    b.HasOne("Artikelsystem.Api.Features.Lieferant.Models.Entitys.Lieferant", "Lieferant")
                        .WithMany("Wareneingaenge")
                        .HasForeignKey("LieferantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lieferant");
                });

            modelBuilder.Entity("Artikelsystem.Api.Features.Wareneingang.Models.Entitys.WareneingangArtikel", b =>
                {
                    b.HasOne("Artikelsystem.Api.Features.Artikel.Models.Entitys.Artikel", "Artikel")
                        .WithMany("Wareneingaenge")
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artikelsystem.Api.Features.Wareneingang.Models.Entitys.Wareneingang", "Wareneingang")
                        .WithMany("ArtikelPositionen")
                        .HasForeignKey("WareneingangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Wareneingang");
                });

            modelBuilder.Entity("Artikelsystem.Api.Features.Artikel.Models.Entitys.Artikel", b =>
                {
                    b.Navigation("ArtikelStatistik");

                    b.Navigation("Wareneingaenge");
                });

            modelBuilder.Entity("Artikelsystem.Api.Features.Employees.Models.Entitys.Employee", b =>
                {
                    b.Navigation("Benefits");
                });

            modelBuilder.Entity("Artikelsystem.Api.Features.Lieferant.Models.Entitys.Lieferant", b =>
                {
                    b.Navigation("Wareneingaenge");
                });

            modelBuilder.Entity("Artikelsystem.Api.Features.Wareneingang.Models.Entitys.Wareneingang", b =>
                {
                    b.Navigation("ArtikelPositionen");
                });
#pragma warning restore 612, 618
        }
    }
}
