// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250416142547_RechteSystem")]
    partial class RechteSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Artikel.Artikel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelGruppeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BearbeitetAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BearbeitetVon")
                        .HasColumnType("text");

                    b.Property<byte[]>("Bild")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErstelltVon")
                        .HasColumnType("text");

                    b.Property<bool>("HistorischGesetzt")
                        .HasColumnType("boolean");

                    b.Property<int>("Maximalbestand")
                        .HasColumnType("integer");

                    b.Property<int>("Menge")
                        .HasColumnType("integer");

                    b.Property<int>("Mindestbestand")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preis")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelGruppeId");

                    b.ToTable("Artikel");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.ArtikelInventurHistorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlteBestandsmenge")
                        .HasColumnType("integer");

                    b.Property<int>("ArtikelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Differenz")
                        .HasColumnType("integer");

                    b.Property<decimal>("DifferenzWert")
                        .HasColumnType("numeric");

                    b.Property<int>("InventurId")
                        .HasColumnType("integer");

                    b.Property<int>("NeueBestandsmenge")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId");

                    b.HasIndex("InventurId");

                    b.ToTable("ArtikelInventurHistorie");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.ArtikelStatistik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BearbeitetAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BearbeitetVon")
                        .HasColumnType("text");

                    b.Property<decimal>("DurchschnittlicherEinzelpreis")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DurchschnittlicherVerkaufspreis")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErstelltVon")
                        .HasColumnType("text");

                    b.Property<decimal>("GesamtVerkaufswert")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric")
                        .HasComputedColumnSql("\"VerkaufsMenge\" * \"DurchschnittlicherVerkaufspreis\"", true);

                    b.Property<decimal>("Gesamtmenge")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Lagerwert")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric")
                        .HasComputedColumnSql("\"Gesamtmenge\" * \"DurchschnittlicherEinzelpreis\"", true);

                    b.Property<int>("VerkaufsMenge")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId")
                        .IsUnique();

                    b.ToTable("ArtikelStatistiken");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.ArtikelZusatzWert", b =>
                {
                    b.Property<int>("ArtikelId")
                        .HasColumnType("integer");

                    b.Property<int>("ZusatzwertId")
                        .HasColumnType("integer");

                    b.HasKey("ArtikelId", "ZusatzwertId");

                    b.HasIndex("ZusatzwertId");

                    b.ToTable("ArtikelZusatzWert");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.Artikelgruppe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProduktkategorieId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProduktkategorieId");

                    b.ToTable("Artikelgruppe");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.ArtikelgruppeZusatzfelder", b =>
                {
                    b.Property<int>("ArtikelgruppeID")
                        .HasColumnType("integer");

                    b.Property<int>("ZusatzfelderID")
                        .HasColumnType("integer");

                    b.HasKey("ArtikelgruppeID", "ZusatzfelderID");

                    b.HasIndex("ZusatzfelderID");

                    b.ToTable("ArtikelgruppeZusatzfelder");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.Produktkategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Produktkategorie");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.Zusatzfeld", b =>
                {
                    b.Property<int>("ZusatzfeldID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ZusatzfeldID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ZusatzfeldID");

                    b.ToTable("Zusatzfeld");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.Zusatzwert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<string>("Wert")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ZusatzFeldID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZusatzFeldID");

                    b.ToTable("Zusatzwert");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.GroupPermission", b =>
                {
                    b.Property<int>("UserGruppenID")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionID")
                        .HasColumnType("integer");

                    b.HasKey("UserGruppenID", "PermissionID");

                    b.HasIndex("PermissionID");

                    b.ToTable("GroupPermissions");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.UserGruppen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserGruppen");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.UserGruppenUser", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("UserGruppenID")
                        .HasColumnType("integer");

                    b.HasKey("UserID", "UserGruppenID");

                    b.HasIndex("UserGruppenID");

                    b.ToTable("UserGruppenUsers");
                });

            modelBuilder.Entity("Domain.Entities.Employees.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseCost")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Benefits");
                });

            modelBuilder.Entity("Domain.Entities.Employees.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .HasColumnType("text");

                    b.Property<DateTime>("BearbeitetAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BearbeitetVon")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErstelltVon")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("SocialSecurityNumber")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Domain.Entities.Employees.EmployeeBenefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BenefitId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CostToEmployee")
                        .HasColumnType("numeric");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BenefitId");

                    b.HasIndex("EmployeeId", "BenefitId")
                        .IsUnique();

                    b.ToTable("EmployeeBenefits");
                });

            modelBuilder.Entity("Domain.Entities.Inventur.Inventur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AbschlussDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BearbeitetAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BearbeitetVon")
                        .HasColumnType("text");

                    b.Property<string>("Bemerkung")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErstelltVon")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Inventuren");
                });

            modelBuilder.Entity("Domain.Entities.Inventur.InventurBerichte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnzahlPositionenMitDifferenz")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BearbeitetAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BearbeitetVon")
                        .HasColumnType("text");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErstelltVon")
                        .HasColumnType("text");

                    b.Property<DateTime>("Erstellungsdatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GesamtDifferenzWert")
                        .HasColumnType("numeric");

                    b.Property<string>("Inhalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InventurId")
                        .HasColumnType("integer");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventurId");

                    b.ToTable("InventurBerichte");
                });

            modelBuilder.Entity("Domain.Entities.Inventur.InventurPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BearbeitetAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BearbeitetVon")
                        .HasColumnType("text");

                    b.Property<string>("Bemerkung")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("DifferenzWert")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErstelltVon")
                        .HasColumnType("text");

                    b.Property<int?>("GezaehlteMenge")
                        .HasColumnType("integer");

                    b.Property<int>("InventurId")
                        .HasColumnType("integer");

                    b.Property<bool>("IstGeprueft")
                        .HasColumnType("boolean");

                    b.Property<int>("Menge")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId");

                    b.HasIndex("InventurId");

                    b.ToTable("InventurPositionen");
                });

            modelBuilder.Entity("Domain.Entities.Lieferant.ArtikelLieferant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("integer");

                    b.Property<string>("ArtikelNrBeimLieferanten")
                        .HasColumnType("text");

                    b.Property<DateTime>("BearbeitetAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BearbeitetVon")
                        .HasColumnType("text");

                    b.Property<decimal>("Einkaufspreis")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErstelltVon")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GueltigBis")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GueltigVon")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IstAktiv")
                        .HasColumnType("boolean");

                    b.Property<bool>("IstPrimaerLieferant")
                        .HasColumnType("boolean");

                    b.Property<int>("LieferantId")
                        .HasColumnType("integer");

                    b.Property<int?>("Lieferzeit")
                        .HasColumnType("integer");

                    b.Property<int?>("Mindestbestellmenge")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId");

                    b.HasIndex("LieferantId");

                    b.ToTable("ArtikelLieferanten");
                });

            modelBuilder.Entity("Domain.Entities.Lieferant.Lieferant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAdresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hausnummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IstAktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notizen")
                        .HasColumnType("text");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PLZ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lieferanten");
                });

            modelBuilder.Entity("Domain.Entities.Warenausgang.Warenausgaenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AllgemeineBemerkungen")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("BearbeitetAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BearbeitetVon")
                        .HasColumnType("text");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErstelltVon")
                        .HasColumnType("text");

                    b.Property<int>("Zweck")
                        .HasColumnType("integer")
                        .HasColumnName("Zweck");

                    b.HasKey("Id");

                    b.ToTable("Warenausgaenge", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Warenausgang.WarenausgangArtikelPositionen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("integer");

                    b.Property<string>("Bemerkung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Gesamtpreis")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Menge")
                        .HasColumnType("integer");

                    b.Property<string>("Rechnungsnummer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Verkaufspreis")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("WarenausgangId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId");

                    b.HasIndex("WarenausgangId");

                    b.ToTable("WarenausgangArtikelPositionen", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Wareneingang.Wareneingaenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AllgemeineBemerkungen")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("BearbeitetAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BearbeitetVon")
                        .HasColumnType("text");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErstelltVon")
                        .HasColumnType("text");

                    b.Property<decimal>("Gesamtpreis")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Wareneingaenge");
                });

            modelBuilder.Entity("Domain.Entities.Wareneingang.WareneingangArtikelPositionen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Einzelpreis")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric")
                        .HasComputedColumnSql("\"Menge\" * \"Gesamtpreis\"", true);

                    b.Property<decimal>("Gesamtpreis")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Menge")
                        .HasColumnType("integer");

                    b.Property<int>("WareneingangId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId");

                    b.HasIndex("WareneingangId", "ArtikelId")
                        .IsUnique();

                    b.ToTable("WareneingangArtikelPositionen", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Artikel.Artikel", b =>
                {
                    b.HasOne("Domain.Entities.Artikel.Artikelgruppe", "Artikelgruppe")
                        .WithMany("Artikel")
                        .HasForeignKey("ArtikelGruppeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikelgruppe");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.ArtikelInventurHistorie", b =>
                {
                    b.HasOne("Domain.Entities.Artikel.Artikel", "Artikel")
                        .WithMany("InventurHistorie")
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Inventur.Inventur", "Inventur")
                        .WithMany()
                        .HasForeignKey("InventurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Inventur");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.ArtikelStatistik", b =>
                {
                    b.HasOne("Domain.Entities.Artikel.Artikel", "Artikel")
                        .WithOne("ArtikelStatistik")
                        .HasForeignKey("Domain.Entities.Artikel.ArtikelStatistik", "ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.ArtikelZusatzWert", b =>
                {
                    b.HasOne("Domain.Entities.Artikel.Artikel", "Artikel")
                        .WithMany("ArtikelZusatzWerte")
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Artikel.Zusatzwert", "Zusatzwert")
                        .WithMany("ArtikelZusatzwerte")
                        .HasForeignKey("ZusatzwertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Zusatzwert");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.Artikelgruppe", b =>
                {
                    b.HasOne("Domain.Entities.Artikel.Produktkategorie", "Produktkategorie")
                        .WithMany("ArtikelGruppen")
                        .HasForeignKey("ProduktkategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produktkategorie");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.ArtikelgruppeZusatzfelder", b =>
                {
                    b.HasOne("Domain.Entities.Artikel.Artikelgruppe", null)
                        .WithMany("ArtikelgruppeZusatzfelder")
                        .HasForeignKey("ArtikelgruppeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Artikel.Zusatzfeld", null)
                        .WithMany("ArtikelGruppeZusatzFelder")
                        .HasForeignKey("ZusatzfelderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Artikel.Zusatzwert", b =>
                {
                    b.HasOne("Domain.Entities.Artikel.Zusatzfeld", "ZusatzFeld")
                        .WithMany("ZusatzWerte")
                        .HasForeignKey("ZusatzFeldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZusatzFeld");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.GroupPermission", b =>
                {
                    b.HasOne("Domain.Entities.Authentication.Permission", "Permission")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Authentication.UserGruppen", "UserGruppen")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("UserGruppenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("UserGruppen");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.UserGruppenUser", b =>
                {
                    b.HasOne("Domain.Entities.Authentication.UserGruppen", "UserGruppen")
                        .WithMany("UserGruppenUsers")
                        .HasForeignKey("UserGruppenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Authentication.User", "User")
                        .WithMany("UserGruppenUsers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserGruppen");
                });

            modelBuilder.Entity("Domain.Entities.Employees.EmployeeBenefit", b =>
                {
                    b.HasOne("Domain.Entities.Employees.Benefit", "Benefit")
                        .WithMany()
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employees.Employee", "Employee")
                        .WithMany("Benefits")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benefit");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Inventur.InventurBerichte", b =>
                {
                    b.HasOne("Domain.Entities.Inventur.Inventur", "Inventur")
                        .WithMany("Berichte")
                        .HasForeignKey("InventurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventur");
                });

            modelBuilder.Entity("Domain.Entities.Inventur.InventurPosition", b =>
                {
                    b.HasOne("Domain.Entities.Artikel.Artikel", "Artikel")
                        .WithMany()
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Inventur.Inventur", "Inventur")
                        .WithMany("Positionen")
                        .HasForeignKey("InventurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Inventur");
                });

            modelBuilder.Entity("Domain.Entities.Lieferant.ArtikelLieferant", b =>
                {
                    b.HasOne("Domain.Entities.Artikel.Artikel", "Artikel")
                        .WithMany("ArtikelLieferanten")
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Lieferant.Lieferant", "Lieferant")
                        .WithMany("ArtikelLieferanten")
                        .HasForeignKey("LieferantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Lieferant");
                });

            modelBuilder.Entity("Domain.Entities.Warenausgang.WarenausgangArtikelPositionen", b =>
                {
                    b.HasOne("Domain.Entities.Artikel.Artikel", "Artikel")
                        .WithMany("Warenausgaenge")
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Warenausgang.Warenausgaenge", "Warenausgang")
                        .WithMany("ArtikelPositionen")
                        .HasForeignKey("WarenausgangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Warenausgang");
                });

            modelBuilder.Entity("Domain.Entities.Wareneingang.WareneingangArtikelPositionen", b =>
                {
                    b.HasOne("Domain.Entities.Artikel.Artikel", "Artikel")
                        .WithMany("Wareneingaenge")
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Wareneingang.Wareneingaenge", "Wareneingang")
                        .WithMany("WareneingangsPositionen")
                        .HasForeignKey("WareneingangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Wareneingang");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.Artikel", b =>
                {
                    b.Navigation("ArtikelLieferanten");

                    b.Navigation("ArtikelStatistik");

                    b.Navigation("ArtikelZusatzWerte");

                    b.Navigation("InventurHistorie");

                    b.Navigation("Warenausgaenge");

                    b.Navigation("Wareneingaenge");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.Artikelgruppe", b =>
                {
                    b.Navigation("Artikel");

                    b.Navigation("ArtikelgruppeZusatzfelder");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.Produktkategorie", b =>
                {
                    b.Navigation("ArtikelGruppen");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.Zusatzfeld", b =>
                {
                    b.Navigation("ArtikelGruppeZusatzFelder");

                    b.Navigation("ZusatzWerte");
                });

            modelBuilder.Entity("Domain.Entities.Artikel.Zusatzwert", b =>
                {
                    b.Navigation("ArtikelZusatzwerte");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.Permission", b =>
                {
                    b.Navigation("GroupPermissions");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.User", b =>
                {
                    b.Navigation("UserGruppenUsers");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.UserGruppen", b =>
                {
                    b.Navigation("GroupPermissions");

                    b.Navigation("UserGruppenUsers");
                });

            modelBuilder.Entity("Domain.Entities.Employees.Employee", b =>
                {
                    b.Navigation("Benefits");
                });

            modelBuilder.Entity("Domain.Entities.Inventur.Inventur", b =>
                {
                    b.Navigation("Berichte");

                    b.Navigation("Positionen");
                });

            modelBuilder.Entity("Domain.Entities.Lieferant.Lieferant", b =>
                {
                    b.Navigation("ArtikelLieferanten");
                });

            modelBuilder.Entity("Domain.Entities.Warenausgang.Warenausgaenge", b =>
                {
                    b.Navigation("ArtikelPositionen");
                });

            modelBuilder.Entity("Domain.Entities.Wareneingang.Wareneingaenge", b =>
                {
                    b.Navigation("WareneingangsPositionen");
                });
#pragma warning restore 612, 618
        }
    }
}
